builds:
  - binary: gyr
    main: ./cmd/gyr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    tags:
      - osusergo
      - netgo
      - static_build
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"
